name: Dilithium3
type: sign
checksumsmall: 8fed102356f42bb67b7985054fba3b4e3df57b5af642315f7287150e57fa5f2c
checksumbig: cfb61892e871497fe67395031e8376fbabd2468ff8046e28abab71fa0fd5ba34
claimed-nist-level: 3
implementations:
    - name: amd64/ref
      version: 0.1
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
    - name: amd64/avx2
      version: 0.1
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
