name: Kyber768
type: kem
checksumsmall: 456bb24a767160dcca466adde267b87f359de6e827d31b5b23512d227d8bbfaa
checksumbig: 8004a42f34a4125acb4f88628139576882cdf9502a77937003e34f52d217a730
nistkat: 89e82a5bf2d4ddb2c6444e10409e6d9ca65dafbca67d1a0db2c9b54920a29172

claimed-nist-level: 3
claimed-security: IND-CCA2
length-public-key: 1184
length-ciphertext: 1088
length-secret-key: 2400
length-shared-secret: 32
principal-submitters:
  - TODO
auxiliary-submitters:
  - TODO
implementations:
    - name: amd64/ref
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags: # FIXME
              - avx2
              - bmi2
              - popcnt
    - name: amd64/avx2
      version: TODO
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
          required_flags:
              - avx2
              - bmi2
              - popcnt
