name: Dilithium5
type: sign
checksumsmall: b1fd5d7815befbe9a254f4d3fd274f90f8b5f3ad245e33e9d4f88c5cdb925af2
checksumbig: a492c5079d70c6d64d10361830fb5367b990346d7778dc35ebc1127749946c09
claimed-nist-level: 3
implementations:
    - name: amd64/ref
      version: 0.1
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
    - name: amd64/avx2
      version: 0.1
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
